include: package:very_good_analysis/analysis_options.yaml

formatter:
  trailing_commas: automate

linter:
  rules:
    require_trailing_commas: false
analyzer:
  errors:
    missing_return: error
    missing_required_param: error

  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true